wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.11
    framework: huggingface
    huggingface_version: 4.33.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695467997.268319
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 23
      4: 3.8.18
      5: 0.15.11
      6: 4.33.2
      8:
      - 4
      - 5
      13: darwin-arm64
